# Meta
name: 은평 살맛나는 마을 지도!
description: 은평 살맛나는 마을 지도는 2016년 은평마을공동체 지원센터에서 제작했고 코드포은평에서 이걸 웹지도로 만들면 재밌겠다 해서 만들어봤습니다. 
url: http://play.codeforep.org
baseurl: ''

timezone: 'Asia/Seoul'
permalink: pretty

# Build
exclude:
  - .jekyll-metadata
  - .gitignore
  - .ruby-version
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE

kramdown:
  input: GFM
  syntax_highlighter: rouge

gems:
  - jekyll-seo-tag

# SEO

author: 코드포은평 codeforep

facebook:
  publisher: https://www.facebook.com/코드포은평-220166888361852/

image:
  facebook: /assets/img/play-ep-screenshot.jpg